COPYING
Use verbatim file from https://www.gnu.org/licenses/gpl-2.0.txt
=> Update FSF addesss in COPYING

contrib/vim.tigrc
This is not meant to merge yet, but to regroup opinions on more Vim-like key bindings to integrate in tig.
Could you guys give it a try and tell me what you think?
I'll push-force your feedbacks on this branch, prefer to look at the global [Files changed](https://github.com/jonas/tig/pull/387/files) view.
Refs #67 #273 #351
=> [RFC] WIP complete Vim-like bindings

NEWS.adoc
=> Add #504 to release notes of v2.2

src/draw.c
=> Fix crash when resizing terminal while search is in progress

doc/tigrc.5.adoc, include/tig/request.h, src/tig.c, test/script/default-test
=> add action view-close-no-quit

doc/tigrc.5.adoc, src/options.c, test/tigrc/source-test, test/tools/libtest.sh
won't pass test suite without ~#611~ ~#615~ #615 was incorporated here.
=> add a -q parameter to source for source-if-present

include/tig/keys.h, src/prompt.c
=> let Ctrl-C exit Y/N and menu prompts

src/string.c
=> raise maximum unicode codepoint

doc/manual.adoc, doc/tig.1.adoc, doc/tigrc.5.adoc, include/tig/request.h, test/help/all-keybindings-test.expected, test/help/default-test, tigrc
We can squash these later but I think the similar #616 suffered from integrating too much.
=> doc linting

Makefile
because some of the existing commands require GNU sed.  In particular, I needed to
```bash
make update-docs SED=gsed
```
=> allow overriding sed executable in makefile

Makefile
per email thread with Ramsay Jones
=> quieten which gsed

test/main/jump-ends-test
`:0` is also possible and somewhat debatable.
=> todo test for bug re: jumping past last line

test/tools/libtest.sh
* correctly find per-kernel suppressions file
* must set IFS to split `$valgrind_ops`
* move suppressions to separate variable to solve quoting issues
* forward tig exit status
=> valgrind test suite fixes

compat/wordexp.c
include the NUL byte in the first `memmove`.
=> fix insufficient memmove in compat/wordexp.c

src/prompt.c, test/main/jump-ends-test
=> don't accept jump command larger than maximum line number

src/prompt.c
It would be nice to also dedupe fully at save time.
=> don't store history empties or consecutive duplicates

test/tools/libtest.sh
as it does not indicate a problem
=> suppress run: message from valgrind

src/io.c
=> child after fork should call _exit not exit

src/graph-v2.c
=> Fix segfault with htab_empty

test/README.adoc, test/tools/libtest.sh
and give feedback as test cases are run:
```
TEST  test/tigrc/width-test
CASE  test/tigrc/width-test:main-widths-default
CASE  test/tigrc/width-test:main-widths-1
CASE  test/tigrc/width-test:main-widths-2
…
```
=> add ability to select tests/cases via TEST_OPTS='filter=<glob>:<glob>'

test/main/refresh-periodic-test
This managed to trip Travis https://travis-ci.org/jonas/tig/jobs/264772034
=> raise timeout in refresh-periodic-test which itself employs sleep

INSTALL.adoc
Added method utilizing Nix package manager
=> Added another installation method

.travis.yml, tools/travis.sh
can also use build stages if needed (only start building autoconf after config has succeeded)
=> parallelize build using travis

test/tools/libtest.sh
now that readline is exposed in tig --version
=> less hacky has_readline test

Makefile, test/API.adoc, test/README.adoc, test/tools/libtest.sh
`test_setup()` doesn't look like it is meant to be exposed, but is called by `gh-490-heap-buffer-overflow-test`.
=> stub docs for testing API

src/refdb.c, test/refs/branch-tag-test
=> Use fully qualified ref name for tag when conflicting with branch name

src/repo.c
=> Fix parsing of git rev-parse output

src/main.c
=> Propagate --first-parent to diff arguments

src/prompt.c
This should solve the problem for now.
The use of the readline() function makes the integration of ncurses and readline a bit hacky. Someday it should be replaced with a proper couple of hook and callback to forward keypresses to readline from the main loop.
=> Fix segfaults with readline 8.0

doc/tig.1.adoc, src/refs.c, src/tig.c
Intended as a first attempt at fixing https://github.com/jonas/tig/issues/694.
=> Add options to filter refs output.

configure.ac
Hello.
This is a PR for making the build work on [IBM i](https://en.wikipedia.org/wiki/IBM_i) - see issue #1051 
Best regards,
Christian
=> Make build work on IBM i

src/display.c
@jonas thx again for awesome tig.
Here is a small change so I can use <Ctrl-^> and <Ctrl-_> in some mappings.
-m
=> Add some range so control chars ^^ and ^_ are also supported

src/tig.c, src/view.c, test/diff/editor-test, test/diff/submodule-editor-test, test/diff/worktree-editor-test
Original PR was in: https://github.com/jonas/tig/pull/1039
I just moved my repo and re-submitted PR.
This change basically keeps cursorline at same position when scrolling, which I think behaves more similar to most other editors.
=> Some minor updates for scrolling and for a double-click in diff

INSTALL.adoc
Tig is a well-established package on FreeBSD:
https://www.freshports.org/devel/tig
=> Add FreeBSD installation instructions

include/tig/options.h, src/diff.c, src/options.c
=> Make word-diff a toggleable option

INSTALL.adoc
=> Add Linux installation instructions

doc/tig.1.adoc, doc/tigrc.5.adoc
Two small improvements I came up with which I think would be useful to users.
=> Doc updates

src/stage.c
Also fix the color of the first split chunk.
Closes #1101
=> Fix navigation between chunks after splitting chunk

src/prompt.c
=> Fix status line when toggling general options

src/pager.c
=> Honor reference-format = hide:tag in diff view

NEWS.adoc, include/tig/git.h, include/tig/parse.h, src/blame.c, src/diff.c, src/parse.c
=> Change the blame view to use porcelain

src/diff.c
This fixes #1192, so see it for more information.
=> Update lineno for untracked files
