src/diff.c

Hi Jonas!
This pull request adds a new `diff_find_header_from_stat()` function used in `diff_common_enter()` and `diff_common_select()` in order to assign the %(file) variable from a diff stat line, which contains the (possibly truncated) filename.
Also use these variables from `diff_common_edit()` so we can now open the editor from a diff stat line.
Fixes the not found issue #404.

Assign variables from diffstat

---

autogen.sh

Heh, I managed to make a typo in branch name when doing initial pull request :)
Original PR: https://github.com/jonas/tig/pull/414

typo: fix in autogen.sh: Leapard -> Leopard

---

contrib/chocolate.theme.tigrc

I haven't seen any other themes in the repository, here is how it looks like : 
I'm not sure if it is possible to colorize the commit messages, but if it is I'd like to colorize them a little bit.
Hope you enjoy it

Add chocolate theme

---

include/tig/util.h

Or if mem is NULL, it will cause segmentation fault.

check if mem is NULL in DEFINE_ALLOCATOR

---

src/blame.c
test/blame/revargs-test

The options parser for blame is currently quite strict, and can handle only a single positive revision in opt_rev_args. But there are several parsing problems with this:
1. If you run `tig blame --reverse foo.c`, the `--reverse`     flag ends up in opt_rev_args (filter_options knows it's a     flag, but since it is a revision flag, it gets put     there).
We try to access `--reverse.c:foo.c`, which is     nonsensical. Moreover, if you did specify a start-point     like `HEAD foo.c`, tig will complain that you have more     than one revision arg.
2. If you run `tig blame --since=123`, this is converted by     `rev-parse --revs-only` to `--max-age=123`, and is     included in opt_rev_args, and you run into the same     problems as above.
3. If you run `tig blame HEAD~20..HEAD`, the commit …

blame: allow user to specify rev arguments to blame

---

doc/manual.adoc
doc/tigrc.5.adoc
include/tig/argv.h
src/pager.c

This exposes the text of the currently selected line as the %(text)
variable. Only the pager view is supported at the moment.
This is particularly handy for using Tig as a scriptable pager. For
instance, here's a dumb remote manager:
$ echo 'bind pager <Enter> git remote show -n %(text)' >> ~/.tigrc
$ echo 'bind pager U git remote update -p %(text)' >> ~/.tigrc
$ git remote | tig
Pressing Enter shows remote information, pressing U fetches the remote.

add a %(text) variable

---

src/tig.c

Fixes an issue where diff full screen diff view up/down navigation results
in moving the underlying commit rather than the diff line if the diff view
had been opened in split format (Enter key) before.

Set view->parent to NULL when view is closed.

---

Makefile
autogen.sh

With this patch, 'make configure' is quieter:
$ make configure
GEN  configure
And if V=1 is specified, then the output is more verbose:
$ make V=1 configure
./autogen.sh
./autogen.sh: running: aclocal -I tools
./autogen.sh: running: autoconf --include=tools
./autogen.sh: running: autoheader --include=tools

Make 'make configure' quieter

---

src/draw.c

- Adjust max_width on each iteration to take account of the column width that has been drawn.
- This issue only manifested itself on very long lines which required more than one invocation of draw_chars i.e. when `length > sizeof(text)`.
- This fixes #500.

Fix drawing long lines in draw_text_expanded

---

src/status.c
test/status/on-branch-tracking-info-test

- Updated `tig status` to show tracking info when appropriate as suggested in #460.
- The `git rev-list` command is used to determine the difference with the remote branch instead of parsing the output of `git status`, as there's no guarantee the format of the latter will remain the same in future.
- Added new test `on-branch-tracking-info-test` based on `on-branch-test` to help ensure this new functionality works as expected.
Below is a screenshot showing the appearance of this feature:

Show tracking info in tig status

---

autogen.sh

Otherwise running `autogen.sh` manually, or using `make configure
--silent` will result in errors:
./autogen.sh: 16: test: =: unexpected operator

Fix error when running with --silent.

---

doc/manual.adoc

By default, in a diff view, the <Up> and <Down> keys move the cursor
in the main view rather than the diff view. Some users will want to
change the default behavior, but not find it immediately obvious
how to do this.

manual: Mention how to change default Up/Down behavior in diff view

---

tools/ax_lib_readline.m4

This fixes found issue on FreeBSD operating system, where libtermcap.so is a link to libncurses.so:
```
% readlink /usr/lib/libtermcap.so
libncurses.so
```
and -lncurses links before -lncursesw, which causes display issues for wide characters:
```
% ldd -a /usr/local/bin/tig | sed -e 's| (.*)$||'
/usr/local/bin/tig:
libreadline.so.6 => /usr/local/lib/libreadline.so.6
libncurses.so.8 => /lib/libncurses.so.8
libncursesw.so.8 => /lib/libncursesw.so.8
libc.so.7 => /lib/libc.so.7
/usr/local/lib/libreadline.so.6:
libncurses.so.8 => /lib/libncurses.so.8
libc.so.7 => /lib/libc.so.7
/lib/libncurses.so.8:
libc.so.7 => /lib/libc.so.7
/lib/libncursesw.so.8:
libc.so.7 => /lib/libc.so.7
```
After applied patch:
```
% ldd -a /usr/local/bin/tig | sed -e 's| (.*)$||'
/usr/local/bin/tig:
libreadline.so.6 …
```

Reorganize checking of libraries for termcap functions

---

contrib/tig-pick

Add tig-pick script

---

doc/manual.adoc

As discussed in #581 this adds a short note to the manual, that mentions `:` can also be used to jump to line.

Explain command for jumping to specific line

---

tools/ax_lib_readline.m4

Previously only the main ncurses libs were checked leading to users with
enabled unicode support (ncursesw) and split tinfo libs running into
segfaults since the checks would fallback to setting TERMCAP_LIB=-lcurses.
Fixes #568.

Check for termcap support in split tinfo libs

---

doc/tigrc.5.adoc
include/tig/options.h
src/search.c
tigrc

New option enables case-insensitive search only if current search
expression doesn't contain any uppercase letters.
This is simple solution which checks only uppercase ASCII letters.
Fixes #320

Add smart-case option

---

src/blame.c

This moves the checking for `-C` to after `opt_blame_options` and (as per the tigrc man page) only sets `opt_blame_options` via the command line if command line arguments were actually given.

Improve blame argument behavior

---

tigrc

Commented sample binding for status-untracked-dirs is updated to the
non-deprecated status-show-untracked-dirs option.

Replace status-untracked-dirs command in tigrc

---

src/tig.c

fixes #321 .  Likely this should always have been button5, instead of button2, per https://github.com/mirror/ncurses/blob/af3d0ee323cbb22d2a7596d564bf68f7307f5076/ncurses/base/lib_mouse.c#L1025

also interpret button5 as wheel-down

---

doc/tigrc.5.adoc
include/tig/options.h
include/tig/request.h
src/tig.c
src/view.c
tigrc

off by default.  setting this to true causes wheel actions to prefer moving the cursor, scrolling the view only when the cursor passes view boundaries.
in present form, will merge conflict with #606

add boolean ~/.tigrc option `mouse-wheel-cursor`

---

doc/tigrc.5.adoc
include/tig/options.h
src/draw.c
src/view.c
test/main/view-split-test
test/tigrc/width-test

* `width` on `line-number` is documented, accepted, but ignored; make it work
* `width` on `status` is documented, accepted, but ignored; remove it
* `width` on `text` is undocumented, accepted, but ignored; remove it
* `width` on `commit-title` is undocumented, accepted, but ignored; remove it
* fix: `width=1` fails when column is trimmed
* add tests for all remaining columns that support `width`
* adjust `main/view-split-test` to match this logic
I simply removed status/text/commit-title because the intent of the design seems to be that these be rightmost and right-filling.  Though it is certainly a reasonable feature to want.
Edit: `view-split-test` was adjusted to fit this, though neither behavior is correct. The UTF-8 logic should be capable of truncating to two visible cells `作者`.

cleanups and tests on view format widths

---

src/prompt.c

Reproducible (but not amenable to the test suite) by
```
:<Enter>
```
which leaves the `:` behind

recognize empty readline input and clear report area

---

src/blame.c
src/view.c

Instead of updating the UI at maximum granularity:
* blame view progress: update titlebar stats every 5 percent
* line-oriented views: update titlebar stats every 100 lines
This little optimization turns out to give a fair gain.  In a very large repo on SSD, the main view completes 0.4 sec faster for me (8% speedup).  Across many small repos I find the gains are always measurable, though almost always less than 0.1 sec.  These values will vary by platform, repo and particularly by terminal emulator.
Even though we are still calling `wprintw()` repeatedly, ncurses is able to notice when the screen contents do not change, and optimize away unneeded writes.

performance: throttle titlebar screen updates during loading

---

doc/tigrc.5.adoc
src/display.c
src/prompt.c
test/help/all-keybindings-test.expected
test/help/default-test
tigrc

* <kbd>Ctrl-C</kbd>, <kbd>Ctrl-V</kbd>, <kbd>Ctrl-S</kbd> would previously have been bindable in the main UI only if the user did some unusual things with `stty` before executing `tig`
* switching to `raw()` mode requires a special case to preserve prior <kbd>Ctrl-Z</kbd> behavior
* <kbd>C-@</kbd> (NUL) is a valid key as far as ncurses is concerned, and useful as a translation of <kbd>Ctrl-&lt;Space&gt;</kbd>
* bindings at the readline prompt are affected by this PR in that *eg* <kbd>Ctrl-S</kbd> becomes available, but the user still must configure those keys separately in `~/.inputrc`: doc that
* <kbd>Ctrl-C</kbd> at the readline prompt is a special case and cannot be bound  in `~/.inputrc`; however we can absorb the `SIGINT` to get intuitive "abort input" behavior. 
* bind …

bindable control characters Ctrl-C, Ctrl-V, Ctrl-S, Ctrl-@, hardcode readline Ctrl-C

---

doc/manual.adoc
doc/tig.1.adoc
src/prompt.c

Persist readline history to `~/.tig_history` or `$XDG_DATA_HOME/tig/history`.
Arguably the `$XDG_DATA_HOME` part doesn't belong in `prompt.c` but this does keep `#ifdef HAVE_READLINE` tucked into a single file.
It might be preferable to persist only the "search" part of the history as `less` does.  Certainly that's the part of the feature I intend to use. However, all readline inputs are currently merged in the volatile history, and I wanted to avoid changing existing UI.
Another desirable refinement would be to take `HISTORY_SIZE` from a `~/.tigrc` option, and support disabling persistent history when set to zero.
It doesn't seem practical to provide test coverage as there isn't a reliable way to inspect the binary for its compile-time readline configuration.

Persistent readline history 

---

doc/manual.adoc
src/prompt.c

Untestable since `save-display` ignores the status area.
Usecase:
```
bind blame   O  @open '%(file)'
bind blob    O  @open '%(file)'
bind diff    O  @open '%(file)'
bind grep    O  @open '%(file)'
bind stage   O  @open '%(file)'
bind status  O  @open '%(file)'
bind tree    O  @open '%(file)'
bind help    O  :echo 'Nothing to open'
bind log     O  :echo 'Nothing to open'
bind main    O  :echo 'Nothing to open'
bind pager   O  :echo 'Nothing to open'
bind refs    O  :echo 'Nothing to open'
bind stash   O  :echo 'Nothing to open'
```

add echo action

---

doc/tigrc.5.adoc
include/tig/line.h
src/line.c
tigrc

`diff-add-highlight` and `diff-del-highlight` become ordinary colors independently governing the fg/bg/attributes of the highlighted cells.
These entries are added to the system tigrc such that the out-of-box configuration is unchanged, though if the user previously customized some diff colors, diff highlight cells will not follow them automatically.
Rationale: independent coloring of four states matches functionality of `diff-highlight` itself. Net reduction of logic.  Dimmer colors for the backgrounded regions are a readability improvement.

make diff-highlight use ordinary configurable colors

---

tigrc

Should have been in #625, didn't realize it was this easy.

pick up diff-highlight colors from git-colors

---

src/tree.c
test/tree/chdir-test

Immediately return `REQ_NONE` after pop on back/parent action in tree-view.  Otherwise back/parent will always perform two actions.
It looks like continuing on to `switch (line->type)` was the correct behavior prior to f893b0a3e.

fix back/parent in tree-view: single pop and return

---

src/argv.c

Incidentally remove unused `pos`.
This was corrupting some strings.  On OS X it's pretty easy to trigger by
```
bind generic n  ?echo "one two" three " " four
```
and then pressing "n" several times.

don't read past end-of-string in quoted case of concat_argv

---

src/tig.c

After #622, the titlebar counts could be stuck lower than the maximum known value if the user did `stop-loading`.

raise titlebar count to highest known item on stop-loading action

---

src/graph-v2.c
test/graph/00-simple-test
test/graph/06-extra-bars-test
test/graph/10-shorter-merge-than-branch-test
test/graph/11-new-branch-in-middle-test
test/graph/15-many-merges-test
test/graph/17-more-merges-test
test/graph/18-tig-test
test/graph/20-tig-all-long-test
test/graph/regression/horizontal-artifact-test
test/graph/regression/horizontal-bar-wrong-2-test

These commits fix a couple of graph display issues. Most issues have been found by running the graph drawing code on a large repo. The added regression tests are initially committed in wrong state and then fixed up to make it easier to visualize the issues they fix.
It also adds two new drawing types for merge commits that are also used as the parent for several other  commits.

Fix graph display issues

---

src/prompt.c

Followup to #626.
I didn't understand the series of transformations in `exec_run_request()`
* https://github.com/jonas/tig/blob/e709657252f9fb09ff97c9cc6e2a159fc370ab27/src/prompt.c#L972-L989
so I did something simpler.  And doesn't the `exec_run_request()` logic discard empty arguments?

expand tig variables in echo action

---

src/display.c

Tested for both optimizations.
Terminal.app is the Apple-supplied terminal emulator, and iTerm2 the most popular OSS alternative.  Both set environment variable `$TERM_PROGRAM`.

enable scroll optimizations for Terminal.app and iTerm2

---

src/graph-v2.c

The graph generation is currently a pretty strcmp() intensive process. By interning strings and replacing the strcmp() invocations by simple pointer comparisons, the graph generation can be sped up by a factor of
four in large repos.

Graph speedup

---

src/diff.c

This also looks vulnerable to filenames containing `|` and should therefore use `strrchr()` as in `diff_common_read_diff_stat_part()`.

improve check for all-space filename in diff stats

---

src/prompt.c

Sometimes `offset` can be -1, while it is also true that screen contents have changed.  Example keystrokes from the main view: <kbd>f</kbd><kbd>&lt;Down&gt;</kbd>, which enters the file-finder, moves the tig cursor, and leaves the terminal cursor out of place.

set cursor coord when not updating prompt contents

---

src/ui.c
test/help/all-keybindings-test.expected
test/help/default-test
test/help/user-command-test
tigrc

This is a special case with its own input handler.  It's also a little annoying that <kbd>C-C</kbd> appears in the help screen for some cases and not for others.
Incidentally it is difficult to figure out that the `search` keymap applies to the file-finder rather than the `/` search.

allow Ctrl-C to terminate file-finder prompt

---

src/display.c
src/grep.c
src/prompt.c

2b384f69b introduced a performance regression due to use of `wclear()`, which dirties the entire screen.  This can be seen in the form of flickering: enter the main view and hold down <kbd>&lt;Up&gt;</kbd>.
The core issue being addressed in 2b384f69b is that readline can leave an incorrect cursor position in virtual window `newscr` (which can be inspected using `getyx()`).
So, explicitly reset the `newscr` cursor position post-readline, which enables switching to the much more efficient `werase()` for erasing the status area.
Incidentally fix the missed case of `report_clear()` after a grep prompt.

report_clear() efficiency, plus clear after grep

---

doc/tigrc.5.adoc
include/tig/options.h
src/draw.c
src/options.c
test/tigrc/truncation-test
tigrc

The `Midline Horizontal Ellipsis` character is exactly for this purpose.  No change to defaults, but the value becomes configurable.
I find the term "delimiter" confusing in this context, but followed the existing wording.

configurable truncation-delimiter w/ utf8 suggestion/special value

---

src/ui.c

It may be possible to optimize some details of `file_finder_draw()`, but this small change improves performance and reduces flicker by avoiding `wclear()` as in #649.
To visualize the flicker: run `tig | pv -qL5000` and hold the <kbd>&lt;Down&gt;</kbd> key.

reduce flicker in file finder; avoid wclear()

---

src/display.c

for users without altscreen-capable terminals
fixes #589
steps to duplicate original issue
* run xterm
* ctrl-middleclick on xterm, making sure that "Enable alternate screen switching" is unchecked in the popup menu
* run bash inside of xterm
* `export PS1='> '`
* `tig`
* issue keystrokes <kbd>&lt;up&gt;</kbd> <kbd>Q</kbd>

erase status line at exit time

---

src/ui.c

~Allocate one more byte for file-finder items~ [edited]
Allocate the full `sizeof(struct file_finder_line)` rather than the size of a pointer, so that there is enough memory for the NUL terminator (and so that the NUL is pre-filled).
Otherwise `strncpy()` will take up the entire space, and tig may later read past the end.

fix string corruption in file finder

---

src/grep.c
src/prompt.c
src/search.c

Fixes #627
xrefs #583 #619 #623 #632 #648
The expectations for `/` search described in #627 match the behavior of `less`, which seems like a good conservative guide.
After this PR <kbd>Ctrl-C</kbd> means "cancel without action" at every prompt, which is accomplished by
* maintaining the distinction between null pointers and strings of length zero, representing canceled input and empty input, respectively. This is somewhat fragile but also intuitive and consistent with most of the existing code paths.
* at the input boundary, capturing the distinction by setting a flag in the readline signal handler as discussed in #623.
* at the input boundary, when configured without readline, changing the way `read_prompt()` calls `read_prompt_incremental()`.  Note that <kbd>Ctrl-C</kbd> is unsupported …

Distinguish between cancel action and empty string at all prompts

---

src/view.c

#622 introduced a regression, which is most visible in a complex blame or tree view: "line 1 of N" or "file 1 of N" is not flushed to the maximum value until the read completes.
The worst case is the tree view in a large repo, which can easily stick on "file 1 of 1" for more than a minute.
This PR addresses the issue by making the granularity of throttling independent for each view.  I'm not sure this is the best fix, though it is generally intuitive that heuristics may adjust per-view.
Perhaps the magic numbers would be as `#define`s with self-documenting names. If so, I wasn't sure if it would be better to scatter them through the per-view headers, or collect the values together.

independent throttle increment for each view

---

src/prompt.c

Not a realistic problem, just better practice. Not sure why I put `curs_set()` inside previously.

signal handler logic should be closest around readline

---

src/prompt.c

Following the interface of `less`, preload the last search from the persistent history at init time, so that the query is immediately available to keystroke <kbd>n</kbd> (`find-next`).
Inherent bug: as discussed in #620, the command and search histories are merged: if the last entry in the history was a command, it will be treated wrongly as a search query.  But this is not different than pressing <kbd>&lt;Up&gt;</kbd> at the search prompt currently.

preload last search from persistent history

---

src/display.c

by ~~reopening the TTY~~ seeking to `SEEK_END`.  Otherwise keystrokes pressed prior to <kbd>Enter</kbd> hang around and can get read later.
To reproduce:
* `:bind generic o !ls`
* <kbd>o</kbd> # *shows listing*
* <kbd>q</kbd><kbd>Enter</kbd> # *leaves `q` unflushed*
* <kbd>o</kbd> # *does not show listing; returns immediately due to unflushed character*

flush buffered keystrokes after external viewer

---

NEWS.adoc
src/display.c

Move the special case of Ctrl-Z introduced in
167d59ed1474e10ec3310fe7aa77314247332954 so no input is generated by
get_input.
---
@rolandwalker does this seem reasonable to you?

Fix #232: Do not generate any input when handling Ctrl-Z

---

test/diff/diff-context-test
test/diff/diff-highlight-color-test
test/graph/gh-490-heap-buffer-overflow-test
test/main/commit-title-overflow-test
test/main/filter-args-test
test/main/no-matching-commmits-test
test/main/refresh-periodic-test
test/main/refresh-test
test/main/show-changes-after-rename-test
test/refs/replace-test
test/refs/start-on-line-test
test/regressions/github-390-test
test/script/default-test
test/stage/gh-410-test
test/stash/start-on-line-test
test/status/file-name-test
test/status/on-branch-test
test/status/on-branch-tracking-info-test
test/status/refresh-test
test/tigrc/contrib-tigrc-test
test/tigrc/tigrc-manpage-examples-test
test/tigrc/xdg-config-home-test
test/tools/libgit.sh
test/tools/libtest.sh
test/tools/setup-conflict.sh
test/tools/show-results.sh
test/tree/file-name-test

Not sure you will agree with all of these.  A few cases border on POSIX matters but most are defensive driving WRT whitespace and punctuation.  No functional change.
* doubledash before constructs which may lead with dash
* `cat <` idiom similar to doubledash
* further quoting to avoid word splitting
* prefer `find ... -exec` over `xargs`. `xargs` splits on space and `xargs -0` is non-POSIX
* `while read -r` over `for ... $(cat ...)` to split on linefeed not space
* `mkdir` with `-p` unless `mkdir` is subject of test
* `$*` over `$@` when meaning is concatenation (somewhat pedantic)
* `printf` over `echo` as it is better behaved/defined
* `grep -c` over `wc -l` avoids leading whitespace
* `grep` over `sed`
* constrain grep FAIL/OK patterns to beginning-of-line
* typo in valgrind parameter …

doubledash and similar test suite linting

---

test/README.adoc
test/tigrc/segfault-test
test/tools/libtest.sh
test/tools/show-results.sh

It would be more fancy to run TODOs every time, and report unexpected successes.
Instead this PR creates a `TODO` category which is a simple subset of `skipped`.  TODOs can be executed by adding the string `todos` to `$TEST_OPTS`.
Individual selections within `run_test_cases` are supported, ~~but it would be a bit more work to make the final summary statement have a correct count of skipped TODOs from `run_test_cases`.~~
Edit: updated to 
* count `run_test_cases` TODOs correctly in `show-results.sh`
* include an example usage: a test which currently exercises a segfault

add a TODO test category

---

Makefile
test/tools/libtest.sh

Options were ignored when more than one was present:
```
TEST_OPTS="verbose todos" make test 
```
since IFS was set conditionally https://github.com/jonas/tig/blob/5d86622e4b9c29f6b948c4e463de7b026d4f9119/test/tools/libtest.sh#L18-L21 .
In the refactor, you might not approve renaming `$TIG_TEST_OPTS` to `$MAKE_TEST_OPTS`.  My reasoning was that I kept forgetting which one I was meant to set at CLI.
* force wordsplit by `$IFS`
* `for` loop is easier than `set`/`shift`
* doc space-separation not comma
* accept some user typos
* die on unknown options
* stop Makefile from setting `$TIG_TEST_OPTS` to `@` (which was default unless `make test V=1`)
* recast `$TIG_TEST_OPTS` as `$MAKE_TEST_OPTS`
* always set `$MAKE_TEST_OPTS` in Makefile; user interface is `TEST_OPTS`

make $TEST_OPTS respect wordsplit under bash

---

compat/hashtab.h
contrib/config.make-CYGWIN_NT-6.1
contrib/tig-completion.bash
include/tig/line.h
src/diff.c
src/draw.c
src/main.c
src/status.c
src/string.c
src/tig.c
test/help/all-keybindings-test.expected
test/main/filter-args-test
test/tigrc/width-test
tigrc
tools/release.sh

A general whitespace cleanup offered as an apology for bungling the indents in `test/tigrc/width-test`.  Cleanup tends to reduce merge conflicts over the long term though it usually creates some in the short term.
* tabs instead of spaces to indent
* tabs instead of spaces to delimit columns
* rm spaces interior to tabs
* rm trailing space
* rm stray linefeeds
* add missing indents

whitespace linting

---

.travis.yml
doc/tigrc.5.adoc

Moves the note about limitations when staging chunk/lines (#590) from
2eec9a58fe08b733819c0bae9eb459a605ea5c59 to the documentation for
"ignore-space".

Ensure that `make update-docs` is up-to-date

---

src/display.c

Clear the terminal before calling out to an external command so the
altscreen won't mess up any downstream subshell management. Restore
terminal settings as per init_display when restoring. Reproducible with
example from[0]:
- Run `tig status`
- Press 'e' to open Vim
- Press Ctrl-Z to suspend Vim
- Run `fg`
- Quit Vim
[0] https://github.com/jonas/tig/issues/232#issuecomment-313790438
Refs: #232
cc: @commonquail

Fix suspension capability when calling out to external commands

---

INSTALL.adoc
Makefile
compat/compat.h
compat/wordexp.c
config.make.in
configure.ac
contrib/config.make
include/tig/io.h
src/display.c
src/io.c
src/options.c
test/tigrc/source-test

In #168 you expressed concern about platforms without `wordexp()`.  Without being sure what those platforms would be, I included a `compat_wordexp()` that can only expand `~/`.
I think the `compat_wordexp()` here is OK so far as it goes, but `expand_path()` is clunky at best.
`wordexp()` is a standard, but it's a lousy standard.  It does several types of transformation, such as arithmetic expansion, and exposes an off switch for only one type (`WRDE_NOCMD` for command expansion).  So `expand_path()` constrains `wordexp()` by constraining its inputs and rebuilding the result.
All that's gained is the rarely-used `~username` expansion, and the ability to use the word "standard".  Though it would be nice to have expansion in more places, like `bind generic * :script …

wordexp() support and compat fallback

---

src/diff.c

#625 introduced a regression: when `diff-highlight` is active, the trailing background color can run to the end of line.  Example: `tig show d4d0825ae`
This PR allows permits a cell of length zero at EOL which changes the color back.
I'm not certain that this won't have other side effects, nor that it is the best way to address the bug.

permit diff cells of length 0, to reset diff-highlight background color

---

doc/tigrc.5.adoc
include/tig/display.h
include/tig/io.h
include/tig/keys.h
src/blob.c
src/display.c
src/io.c
src/keys.c
src/prompt.c
src/status.c
src/view.c
test/tigrc/parse-test

Adds new external command option flag `+`, meaning "echo first line of the output to the status bar".  Unlike `!`, output is integrated into the regular TUI and need not be manually dismissed.
Example usage:
```ini
bind main U +sh -c 'git --no-pager shortlog -s --author="$(git show -s --format=%aE %(commit))" </dev/tty'
```
I think this is a good feature, but recognize that `open_external_viewer()` is taking too many params.
It might be better if the feature was "collapse whitespace and display as much output as fits in one screen width", though the user can get that by appending `| xargs` to a command.
(Odd little bug in `git-shortlog`: no output from the above command without `</dev/tty`.)
Edit: flagname `+`

single-line output of external command to status bar

---

src/keys.c
src/prompt.c
test/prompt/exec-test

Bug: segfaults on `:exec` (no args) and `:exec !` (flags but no actual command args).
Created a directory `test/prompt/` here, which is debatable, since the included tests don't work by stuffing keystrokes.  But it would be a good thing for the test suite to learn how to stuff keystokes, and populate a proper `test/prompt/`.

don't segfault on :exec irregular arguments

---

src/display.c
test/tools/libtest.sh

The entire test suite provides coverage after removing a sed directive.

tolerate empty lines in scripts

---

NEWS.adoc

very slightly improved in `:source` but not news-worthy

tilde expansion was added to :script

---

src/refdb.c
test/tigrc/builtin-save-test

which happens if attempting to write out the builtin config.  Fixes segfault todo from #664.

save-options able to write empty reference_format

---

test/tools/valgrind-Darwin.supp

Initializing `we_result` doesn't affect the warning:
```
Conditional jump or move depends on uninitialised value(s)
at 0x1003EF302: strstr (in /usr/lib/system/libsystem_c.dylib)
by 0x1003F0987: wordexp (in /usr/lib/system/libsystem_c.dylib)
by 0x100005FB2: expand_path (io.c:156)
```

suppress valgrind warning within darwin libsystem

---

test/help/all-keybindings-test
test/main/branch-var-test
test/main/graph-argument-test
test/refs/branch-var-test
test/status/repo-var-test
test/tools/libtest.sh

`assert_vars` was a bit vulnerable to false positives, and unable to test on whitespace.
* take second arg of `assert_equals` for whitespace strict/ignore. Notes are still on trailing args.
* rewrite the `assert-vars` inline script: less likely to trivially exit, save empty strings as literal `""`
* run at least one test after `assert-vars` to ensure that steps-script completes
The last is a bit of a hack, though it harms nothing.  Better would be for the `assert_vars` shell function to accept an argument for the number of variables tested (number of lines in the vars file).

tighten up assert_vars testing

---

src/display.c
test/script/comment-test

Did not change doc.  In the absence of a Scripts section, the user's assumption is likely that scripts are similar to `~/.tigrc` files.

ignore script lines starting with # (comment)

---

include/tig/tig.h
src/io.c

This fixes a race condition which can be exercised readily on OS X by
``` bash
for i in $(seq 1 100); do make test/main/filter-args-test; done
```
It's of little importance to users but probably manifested as an occasional mystery glitch in Travis.

ensure ordered writes to trace file

---

doc/tigrc.5.adoc
include/tig/options.h
src/prompt.c
src/tig.c
tigrc

0 to disable the feature.
This could be tested decently once libtest.sh supports stuffing keystrokes.

history-size tigrc option

---

Makefile

To quickly select only the TODO tests, and also actually run them.

add test-todo make target

---

test/main/all-arg-test
test/main/branch-var-test
test/refs/branch-var-test
test/status/repo-var-test
test/tools/libtest.sh

This defends against silent failures, since both `vars` and `expected/vars` have been filled by the same action.
Other followups to #707 
* `-w` is a clearer default value for `$whitespace_arg`
* fix stub `"message"` param left from dev

require expected-asserts count argument to assert_vars

---

src/prompt.c

Some shells expose an option to control deduplication, but I think it is just common sense.
Incidentally fix prompt_teardown from firing when history-size is 0.

fully deduplicate history on save

---

test/README.adoc
test/tools/libtest.sh

Timeouts are a prerequisite for tests to be able to drive tig by simulating keystrokes.
Core sections of `run_test_cases` and `test_tig` simplified via use of subshells.
Timeouts disabled under valgrind since this combination is so far untested.

timeouts on external processes in test harness

---

test/status/on-branch-test
test/status/on-branch-tracking-info-test
test/tools/libtest.sh

After #688 there are a few glitches in Travis
* https://travis-ci.org/jonas/tig/jobs/263825104
* https://travis-ci.org/jonas/tig/jobs/263825140
* https://travis-ci.org/jonas/tig/jobs/263825141
`on-branch-test` is failing each time with a timeout, under valgrind.  The failure happens in a fairly long synthesized tig script.
This PR
* adds a timeout bonus to all tests under valgrind
* adds a `test_timeout()` function which should have been in #688
* raises the timeout on the relevant sections of `on-branch-test` and the related `on-branch-tracking-info-test`

Test timeout followups

---

test/tools/libtest.sh

`-s` test no longer needed.  This was exercised by `assert_vars()`

avoid writing to filename that may also be the content source

---

test/tools/libtest.sh

If the user didn't specify content for STDERR, that is the same as specifying it must be empty

bug: branch on content in expected file

---

test/tools/libtest.sh

* remove bash-dependent setting
* always use space+tab when wordsplitting is wanted
* set IFS for `git diff` where worksplitting is wanted (bug)
As a matter of opinion, I think it is better not to manipulate IFS at all but to follow shell quoting rules.

consistency in use of IFS

---

test/tools/libtest.sh

so that they don't linger after running tests

convert test timeout watchers to polls

---

test/tools/libtest.sh

save/restore TTY attributes in test suite

---

include/tig/tig.h
src/display.c

main program:
* `opt_tty` becomes a struct
* `tcgetattr()` at init time
* `tcsetattr()` in `done_display()`
* specify `TCSAFLUSH` action in `done_display()` so that tig can't leave keystrokes behind
`open_external_viewer()`, after running external command:
* restore init-time tty attributes before duplicating ncurses setup steps
* use `TCSAFLUSH` action when restoring tty attributes to block keystrokes leaking in from external command phase - probably more robust than `fseek()` on the file pointer
* but keep `fseek … SEEK_END`, which does no harm, make it unconditional
edit: also set tty attributes and flush before running external command

save and restore TTY attributes

---

NEWS.adoc
src/display.c

Reverts part of c883298355e02fc2c431cb68fe5edc212ec62fea to ensure
pasting into the prompt works for ncurses 5.4.
Fixes #767

Use initscr to ensure proper TTY setup for the prompt

---

src/display.c

Currently, when \n is received, tig will report
"Unknown key, press h for help"
This is a workaround for vim/vim#1998 but nevertheless it might make
sense to handle \n synonymous to \r. So this patch makes handling \n
like \r.

Handle \n like \r

---

doc/tig.1.adoc

It looks at XDG_DATA_HOME for tig history, not XDG_CONFIG_HOME

Fix env var checked

---

src/display.c

This reverts commit e22d8060baebc61a7cc20642f6e6c9c304f2b9a5 in order to restore the distinction between `<enter>` and `<c-j>`. 
See https://github.com/jonas/tig/pull/758.

Revert "Handle \n like \r (#758)"

---

contrib/config.make-CYGWIN_NT-6.1

Cygwin has apparently updated the `ncursesw` package to version 6.
Update make config to reflect that.

Update make config for cygwin/ncurses

---

doc/tigrc.5.adoc
include/tig/options.h
src/tig.c
tigrc

Can be set to "no" to disable sending enter key presses to child view.
In practice only relevant if "focus-child" is false.
Default is "yes", which is identical to previous behavior.

New boolean option "send-child-enter"

---

src/io.c

file -I works with macOS but not with Linux (should be file -i). Rather use the long option --mime which is valid for both.

Fix file argument

---

src/display.c

refresh is implement as a macro in netbsd curses,
so using it as a variable name clashes.

display.c: fix build with netbsd-curses

---

include/tig/display.h

`newscr` is a ncurses-ism, and doesn't exist in netbsd-curses.
according to `man 3x curs_variables`:
> The New Screen
> This implementation of curses uses a special window newscr to hold  up-
> dates to the terminal screen before applying them to curscr.
so it seems using curscr instead should be fine.

display.h: fix build against netbsd-curses

---

src/graph-v2.c
src/grep.c
src/options.c
src/view.c

I tried compiling tig with most warnings enabled using the current gcc snapshot that would become gcc 8. I started with `-Wall -Wextra` and disabled warnings that cannot be easily fixed (`-Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers`)
I was able to fix all warnings, but some fixes need more work, so I'm only submitting the simple and good-looking fixes.

Warning fixes

---

src/ui.c

If no text is found in the file search, pos->lineno would become `(unsigned long)-1` which would lead to invalid memory access in `file_finder_draw()`

Don't allow pos->lineno to underflow in file search (#800)

---

include/tig/draw.h
src/draw.c
test/grep/default-test
test/grep/start-on-line-test

Disable the addition of number of scrolled lines to the line number in
"grep" mode, as the line numbers in this case actually are search
results, and not line numbers of e.g. a viewed file.

Fix line numbers in grep view when scrolled

---

include/tig/git.h

Pass command line args through to the stage view

---

src/graph-v1.c
src/graph-v2.c
test/diff/diff-stat-split-test
test/graph/00-simple-test
test/graph/01-merge-from-left-test
test/graph/02-duplicate-parent-test
test/graph/03-octo-merge-test
test/graph/04-missing-bar-test
test/graph/05-extra-pipe-test
test/graph/06-extra-bars-test
test/graph/07-multi-collapse-test
test/graph/08-multi-collapse-2-test
test/graph/09-parallel-siblings-test
test/graph/10-shorter-merge-than-branch-test
test/graph/11-new-branch-in-middle-test
test/graph/12-cross-over-collapse-test
test/graph/13-collapse-parallel-branches-with-different-middle-branch-test
test/graph/14-long-collapse-line-test
test/graph/15-many-merges-test
test/graph/16-changes-test
test/graph/17-more-merges-test
test/graph/18-tig-test
test/graph/19-tig-all-test
test/graph/20-tig-all-long-test
test/graph/regression/horizontal-artifact-test
test/graph/regression/horizontal-bar-wrong-2-test
test/main/commit-order-edge-case-test
test/main/graph-argument-test
test/main/start-on-line-test

by returning smaller character "Bullet Operator" for ordinary commits

visually distinguish merges vs ordinary commits in utf8 graph

---

include/tig/display.h
src/display.c
src/prompt.c

Readline was causing major perf issues when interpreting a script, and inappropriately storing each script line in `~/.tig_history`.

sidestep readline when executing a script

---

doc/tigrc.5.adoc
include/tig/options.h
src/draw.c
src/view.c
test/tigrc/width-test
tigrc

Rationale: certain columns are derived from data sources which are free and difficult to tame.  I regularly use a repo containing a commit with a mangled `author` field of length 575 characters.  Once merged into a shared repo, this is not practical to alter.  There are similar length issues with formalized branch names in large organizations.
The `width` parameter is rigid, and was somewhat misleadingly documented. `author,width=30` wastes screen when opening any other repo, whereas `author,maxwidth=30` is reasonable in all cases.
But I'm not sure about the interface proposed in this PR.  Perhaps you would rather
* change `width` to behave as maximum width, following the existing documentation, or
* have `maxwidth` available on all fields where `width` is possible, or
* have `maxwidth` …

rfc: add `maxwidth` format param for fields `author`, `file-name`, `ref`

---

snap/snapcraft.yaml

This package will let you publish the latest tig in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

 Add the packaging metadata to build the tig snap

---

src/prompt.c
test/README.adoc
test/main/search-preload-test
test/tools/libtest.sh

`string_copy()` respects `sizeof()` on its source rather than `strlen()`, truncating the preloaded search string to the sizeof a pointer.
This fixes it, though I actually don't understand why `string_copy()` wouldn't consult `strlen()`.

untruncate preloaded search string

---

Makefile
configure.ac
include/tig/apps.h
include/tig/io.h
include/tig/tig.h
src/apps.c
src/argv.c
src/diff.c
src/display.c
src/io.c
src/options.c
src/prompt.c
test/diff/diff-highlight-test
test/tools/valgrind-Darwin.supp

`diff-highlight` lives under contrib and is probably not on the user's `$PATH` in most installs

let `set diff-highlight=true` work when the diff-highlight executable is not on $PATH

---

include/tig/display.h
src/display.c
src/tig.c
test/README.adoc

Make tig the process-group leader and give it the foreground connection to the TTY.  This announces to the OS "I am the interactive program taking input".
Being process-group leader allows for a simple and robust idiom for cleaning all child processes at exit time: tig can signal HUP to the entire process group (which tig can be certain that it owns).  While tig doesn't intentionally keep very long running child processes, it does depend on child processes quite a bit, so this cleanup is just good practice.
As noted in `test/README.adoc`, this PR adds a minor issue: if the user sets `stty tostop` in their interactive shell, then tig's test suite will not be able to run.  Actually, it will run, but then constantly stop again as output is generated.  That is as intended for `stty tostop`: …

Make tig the process group leader and automatically clean child processes

---

contrib/tig-pick

Current version doesn't work for my environment (bash bundled with macOS):
$ sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
The result commit is printed to stderr instead of stdout. I can't pinpoint the
problem but other traits in the script suggest that it is intended for bash
anyway. And it works fine with explicit bash for me.

Fix tig-pick output redirection

---

src/tig.c

I believe issue #802 is the main reason why so many people ask about remapping up and down keys. If the current behaviour is actually a feature maybe a parameter can be introduced.

Fix incorrect behaviour of up and down keys in diff view when opened from diff preview

---

src/tig.c

The problem occurs when you have staged or unstaged changes in the repository and is mostly visible when diff-highlight is true. If you press d or enter in the main view it will automatically switch to stage view while if you press d from the split view it opens diff view and you get an annoying "Failed run the diff-highlight program: diff-highlight". For consistency, switch to stage view as it is done for the main view when there is no commit associated to the selected line.

Fix error when trying to open diff view from split view on (Un)staged changes line

---

src/display.c

Vim seems happier when we set the foreground process group ID back to its original value before leaving. Sounds logical when it's written like that actually.

Fix Vim going background after running Tig

---

configure.ac
src/prompt.c
tools/ax_lib_readline.m4

Mininum Readline version is now 6.3 due to the use of the
rl_change_environment variable.
Also fixed check against major required version and added support for
configure --without-readline.

Fix resize not working after entering command (#845)

---

include/tig/line.h

Taking benefit of the half time break, here is one more patch. This was the last recurring annoyance I encounter with tig. Do you plan a new release soon ?

Fix deleted file mode line remains highlighted after hovering in diff or stage view

---

NEWS.adoc
config.make.in

According to `tools/ax_with_curses.m4` `CURSES_CPPFLAGS` was renamed to
`CURSES_CFLAGS` for compatibility with `pkg-config`, so add the flags to
`CPPFLAGS`.
References Linuxbrew/homebrew-core#8440

Fix #856: Add CURSES_CFLAGS to CPPFLAGS

---

tigrc

Simply add missing description of  `+` prefix for user-defined command which is in man page

Add synchronous command description in tigrc

---

src/options.c

The official `git config` uses `ul` for `underline`.
It is this setting that is used by `diff-highlight` or `diff-so-fancy`.
The change allows for `.gitconfig` that works for both `tig` and `diff-highlight`
There is probably a better manner or place to do it, I am not very fluent in C.
It could also be possible to use a separate `diff-add-highlight color color underline` in `.tigrc`. In this case `.tigrc` should take precedence over `.gitconfig` (this is not in effect currently).

Git diff colors: interpret 'ul' as 'underline'

---

src/view.c

cppcheck reports:
[view.c:1679]:
(error) Common realloc mistake: 'box' nulled but not freed upon failure
Indeed, writing the result of realloc() to its first argument is a bad
practice. It is OK here only because box and line->data are equal when
realloc() is called. Even if box becomes NULL, line->data survives.
To avoid the confusion, initialize box with the result of realloc(). Use
line->data until that point.

Fix incorrect cppcheck warning about realloc() use

---

include/tig/view.h

cppcheck reports an issue in tig:
[view.h:75]:
(error) Shifting signed 32-bit value by 31 bits is undefined behaviour
There is no good reason to make VIEW_RESET_DISPLAY the largest value in
enum. Just use 1 << 17 for it, which is the next available power of two.

Don't shift signed int by 31 bits

---

src/tig.c

Since commit ed36f75 (Add -C option to specify the working directory, 2019-03-21), we allow:
```
tig -C/path/to/repo
```
to change into the repo directory before running any git commands. But because of the way tig's command-line parser works, this eats any "-C" we meant to pass to a git command, like:
```
tig blame -C foo.c
```
which used to enable copy-detection in the blame. Let's require that -C come before any sub-command. That will continue to allow:
```
tig -C/path/to/repo
```
with no subcommand. It also means that using "-C" with a subcommand looks like this:
```
tig -C/path/to/repo blame foo.c
```
which matches git's global -C option to change directories. And of course it allows:
```
tig blame -C foo.c
```
to work as it used to prior to ed36f75, enabling copy detection.

only accept "-C" before a subcommand

---

include/tig/status.h
src/main.c
src/stage.c
src/status.c
src/tig.c
src/watch.c
test/main/untracked-test

Following discussions with @proski in #762, I decided to give a try to a "Untracked only" status view when called from the Untracked changes line. Having in mind the use case of checking quickly which files were left behind, this version seems indeed better than opening the regular status view and moving the cursor to the Untracked files currently implemented.
@jonas, the refresh part surely needs to be reviewed.

Untracked only status view

---

src/display.c
src/tig.c
src/watch.c

This PR should improve the current situation or, at least, make all the modes do something. There are still some (pre-existing) problems remaining but none of them is related in the existing issues. 
As I don't use the periodic mode personally, I didn't look further but it looks to me that in this mode Tig refreshes unexpectedly 2 or 3 time at startup (hence the claim that it was working sometimes). Not the end of the world but for large repos it can be annoying.
The special handling of the stage view prevents a correct refresh of the status view in some cases.

Improve behaviour of auto and periodic refresh modes

---

doc/tigrc.5.adoc
include/tig/git.h
include/tig/line.h
src/draw.c
src/main.c
src/options.c
src/refs.c
test/main/filter-args-test
tigrc

Show annotated commits title in main-annotated color (the default
configuration in tigrc uses "default default bold" to follow the
same logic as tags). You can choose a different notes tree using
tig --notes=foo. To see all notes, use tig --notes=*.
Closes #819

Show annotated commits in main view

---

src/graph-v2.c

When the `main_done()` is called, `done_graph()` is called, which calls `free(graph)`, where `graph` is a pointer to a `struct graph`. `struct graph` points to a hash table `colors.id_map`, which should be freed before `free(graph)` is called.
The memory leak can be induced in the main view by defining the keybinding on the prompt line `:bind main t !t true`, where `true` is essentially a shell no-op. Pressing `t` in the main view and then quitting will get a LeakSanitizer report of a direct leak. The leak happens for each `t` command so that the amount leaked is proportional to the number of times `main_done()` is called.
> Direct leak of 112 byte(s) in 1 object(s) allocated from:
>     #0 0x7effa34b7d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
>     #1 …

Fix memory leak in main view

---

Makefile
doc/manual.adoc
doc/tig.1.adoc
doc/tigrc.5.adoc
include/tig/options.h
include/tig/reflog.h
include/tig/tig.h
src/reflog.c
src/tig.c
src/view.c
test/help/all-keybindings-test
test/help/all-keybindings-test.expected
test/help/default-test
test/help/user-command-test
test/reflog/default-test
tigrc

Press L to open the reflog view or start with tig reflog.
The main benefit over git reflog --pretty=raw | tig --pretty=raw
is the ability to browse the full chain of commits for each reflog.
Closes #538

Introduce reflog view

---

tools/make-builtin-config.sh

read_tigrc() uses an unportable sed expression at them moment as
`\s` is silently ignored in BSD sed and actually just matches `s`.
In the future this may become a fatal error on FreeBSD.
`[[:space:]]` should work just as well on Linux or elsewhere while
actually doing what was intended (strip leading whitespace) on
FreeBSD.
Downstream bug report:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233423

make-builtin-config: Fix unportable sed usage in read_tigrc()

---

src/diff.c

Combined diff chunks start with '@@@', use that to detect them instead of
the "Merge:" field that is present for all merges, regardless of diff type.
Technically, this still doesn't handle merges with more than 2 parents
but that's not a regression
From git-log(1):
4. Chunk header format is modified to prevent people from
accidentally feeding it to patch -p1. Combined diff format was
created for review of merge commit changes, and was not meant
for apply. The change is similar to the change in the extended
index header:
@@@ <from-file-range> <from-file-range> <to-file-range> @@@
There are (number of parents + 1) @ characters in the chunk
header for combined diff format.
Closes #941

Properly detect combined diffs

---

src/prompt.c

Whenever a view column option is toggled, the new setting is echoed on the status line, but it does not mimic what should be typed on the status line using the set command to achieve the same thing.
For example, the message `set commit-title-graph = v1` is shown but the user needs to type `:set main-view-commit-title-graph = v1` on the status line to achieve the same setting, _ie_, the user needs to type a colon to initiate command mode, and then type the view name as a prefix to the option name.
The PR modifies `prompt_toggle_option()` to show exactly what needs to be typed on the status line. The function called `success()` with a format string, an option name, and an option value to generate a status line for each type of option value. The format string is modified to include …

Improve how a toggle option value is shown on the status line

---

INSTALL.adoc

Added information, that it's now possible to use tig, by plainly installing 'git-for-windows'.

Added additional Windows installation method to documentation

---

doc/manual.adoc

Fix formatting for the "History Files" heading. Fixes #954

Fix typo in manual heading (fixes #954)

---

src/diff.c
src/view.c

* Crash on diff chunk splitting (#523).
* Memory leak on diffing.

Fix two memory issues

---

contrib/tig-completion.bash

Fixes: #795 ("tab completion is really slow")
When run on a Git repository with a large amount of files, like the linux repository, __tig_complete_file() can take a very long time to complete. This is unfortunate because when accidentally pressing Tab in such a repo, bash gets stuck until the completion function has finished, and does not even allow the user to cancel the operation with Ctrl-C.
In contrast, the current git completion does not have these problems, and since tig's command line parameters are mostly parameters to git-log or git-diff, we can use git's native completion for those cases instead. This also has the advantage that we do not need to care about updating the tig completion when new parameters are added to git-log or git-diff.
I have tested this only in bash, not on …

bash/zsh completion: reimplement and decrease runtime by factor 1863

---

src/display.c
src/draw.c
test/main/vertical-lines-test

Putty doesn't show VT100 line drawing characters in the UTF-8 mode by
default. Putty 0.70 and older doesn't even have that option.
For the vertical display separator, use '|' as background, then output
the vertical line character on every line.
For the line number separator, use draw_graphic() in the default mode
only. Use draw_chars() in the ASCII and UTF-8 modes.
Add a test for vertical lines. The display separator is always captured
as a line of '|' characters. The line number separators are captured
correctly. 'x' corresponds to ACS_VLINE.
Closes #981

Fix vertical lines in Putty with UTF-8 graphics

---

src/parse.c

This fixes a rare case of chunk line numbers not being computed
correctly.  It happens when a chunk marking a conflict contains a "-"
in its description:
@@@ -45,7 -45,10 +45,14 @@@ void foo() { // -dash

Fix parsing of three-way chunk headers with extra dashes

---

src/options.c

There is a small typo in src/options.c.
Should read `false` rather than `fale`.

docs: fix simple typo, fale -> false

---

contrib/tig-completion.bash
contrib/tig-completion.zsh

There's a bunch of issues regarding the zsh completion:
* The Zsh bash completion emulation was loaded at the wrong time
* The Git bash completion helpers were not used correctly
* The Zsh bash completion emulation can't be relied upon
These changes should fix the issues mentioned in pull #960 and #940.

Zsh completion fixes

---

contrib/tig-completion.bash

Addresses https://github.com/jonas/tig/issues/1011
As identified in https://github.com/jonas/tig/issues/1011#issuecomment-736922515, there are cases where `__git_complete` is undefined because it is loaded dynamically by bash_completions.
As suggested in https://github.com/jonas/tig/issues/1011#issuecomment-736938541, using `pkg-config` to find `git-completion` script, which defines `__git_complete`.  And using approach similar to https://github.com/felipec/git-completion/blob/master/git-completion.zsh#L28-L49

Handle undefined __git_complete

---

NEWS.adoc
include/tig/diff.h
include/tig/status.h
src/diff.c
src/stage.c
src/status.c

When starting a blame in the stage view on a deleted line, it seems
appropriate to find the commit that added the line.  To this end, instead
of starting the blame view from the working-tree-state of a file, use
the version at HEAD, which still has the deleted line (unless the line
was only just staged).  Compute the position of the deleted line to
start the blame view there.
Closes #1008

Blame uncommitted deletions starting from HEAD

---

NEWS.adoc
doc/tigrc.5.adoc
src/options.c
tigrc

Add line-graphics = auto

---

NEWS.adoc
src/repo.c
test/main/all-arg-test
test/reflog/default-test
test/refs/branch-checkout-test

Update tracking branch when refreshing status view

---

NEWS.adoc
doc/tig.1.adoc
src/stash.c
src/tig.c

As the stash reference does not necessarily match the line number anymore,
take it from the output of git stash list.
Closes #1022

Pass stash args through

---

NEWS.adoc
include/tig/view.h
src/draw.c
src/main.c
src/view.c
test/reflog/default-test

That way, you can better figure out identical references when browsing
the reflog view. Show the reflog name in the title window instead. In
the stash view, the id column also shows the commit id instead of the
reference.
Closes #1025

Use id column for commit id only

---

src/display.c

This is a fix required since the PR of: https://github.com/jonas/tig/pull/1041
We need to also skip when key_value is KEY_ESC so it is not set to a control key.

Fix for PR 1041 - add check for key_value != KEY_ESC

---

src/diff.c

I found this when working on the CI, running, see
https://builds.sr.ht/~krobelus/job/388884 which runs
CC=clang TIG_BUILD=config.make tools/travis.sh
The warning from clang was:
src/diff.c:377:27: error: converting the enum constant to a boolean [-Werror,-Wint-in-bool-context]
(type = LINE_DEFAULT ||

Use comparison instead of destructive assignment

---

src/parse.c
test/diff/line-number-test

Usually diff hunk headers look like "@@ -a,b +c,d @@" where "a" is the
starting line number and "b" is the number of lines in the preimage of the
hunk. Same for "c" and "d" except they refer to lines in the postimage.
Git omits "b" and "d" if they are 1.  Tig already treated "b" as optional but
not "d". We can simply ignore a missing number because "header->new.lines"
is already initialized to 1 in parse_chunk_header().
$ echo old line 1 >? old
$ echo new line 1 >? new
$ git diff --no-index old new | tail -n3
@@ -1 +1 @@
-old line 1
+new line 1

Fix %(lineno) computation for hunk postimages that span only one line

---

doc/manual.adoc
doc/tigrc.5.adoc
include/tig/request.h
src/tig.c
src/view.c
test/help/all-keybindings-test.expected
tigrc

Add scroll-half-page-up and scroll-half-page-down actions

---

.gitignore
Makefile

This is useful for some Clang-based tools, in particular language servers like clangd or ccls.
I mostly took this mostly from Git's Makefile.  The awkward if-statement
is because the "missing_compdb_dir" trick that Git uses didn't work for
some reason.
Keep in mind that not all compilers support the -MJ option. Clang does, so this
command should give you a fresh compile_commands.json
make CC=clang GENERATE_COMPILATION_DATABASE=yes clean all-debug

Allow to generate a compilation database

---

test/main/emoji-test

test/main/emoji-test fails for me at emoji-commit-titles-col-300 because
this line is not rendered correctly:
2009-04-06 01:44 +0000 Committer o [master] 🌏💧✋🕋🗡🚀🏜☀️🌡🌶💯🚱⏳🌅🌑😡💉😱😈💀💥🌛🌙🐭💥🚶🏻〰🐛️⌛️👳🙏💥😴🛌😳💥🐛💥👊⚔👑
The line in emoji-test contains two [🐛emojis](https://unicode-table.com/en/1F41B/).
However, the first bug is followed by an invisible ["Variation Selector"](https://unicode-table.com/en/FE0F/).
Here are the two bugs with a \uFE0F in the middle:
🐛️🐛
It looks like Tig renders the first bug without \uFE0F, but the test
expects it.
The same goes for the next visible character after the first bug: ⌛ is
also followed by \uFE0F which is not rendered.
Fix the test failure by removing both invisible characters from the expected output.
This approach will probably break the test on other systems. I …

Fix test failure due to not displaying invisible characters

---

NEWS.adoc
doc/manual.adoc
doc/tigrc.5.adoc
include/tig/argv.h
src/diff.c

I use Tig to write review comments on GitLab (hopefully soon GitHub as well).
To comment on specific lines of a diff, the GitLab API requires both the
line number _before_ the diff, and _after_ the diff.  Additionally, it needs
the line type (added, deleted / context line). This patch exposes %(lineno_old)
which is the dual to %(linenno). It could also be useful when viewing
"reverse" diffs.

Expose the line number before a diff as %(lineno_old)

---

src/diff.c

Previously we'd only update %(text) in the header of the diff view.  Also
update %(text) when inside the diff contents. This allows to determine if
the current line is added, deleted or context, which allows to give precise
location information when talking to the GitLab API for example.

Update %(text) when navigating diff contents

---

src/argv.c
src/blame.c
src/diff.c
src/display.c
src/draw.c
src/status.c
src/ui.c
src/util.c
src/view.c

Format time_t values portably and fix other values too

---

src/string.c

Fix loop when wrapping line with ISO-8859-1 character

---

doc/tig.1.adoc
doc/tigrc.5.adoc
src/display.c

Add TIG_EDITOR environment variable to configure editor

---

src/argv.c

This makes it possible to use tig -L:argv_parse_rev_flag:src/argv.c
to browse all commits updating argv_parse_rev_flag() in argv.c.

Fix parsing of -L argument

---

src/log.c
src/options.c
test/main/filter-args-test
tigrc

Also improve consistency when mailmap is disabled.
Closes #1104

Enable mailmap by default to match git log's behaviour

---

src/string.c

I found that `set ignore-case = smart-case` does not work when searching a term that includes the space character, e.g., searching 'foo bar' does not match 'Foo Bar'.
- This is because [the category for space](https://github.com/JuliaStrings/utf8proc/blob/93a88b43107eccf09eea399a3b7a6767092d4488/utf8proc.h#L304) is `UTF8PROC_CATEGORY_ZS`, which has the value 23, aka 0x17, or 0b10111, and the smart-case test, `utf8_string_contains_uppercase`, which calls `utf8_string_contains`, is [using bitwise AND to check the category](https://github.com/jonas/tig/blob/master/src/string.c#L323):
```
if (property->category & category)
```
So then the space character -- category 0x17 -- matches [the uppercase category](https://github.com/JuliaStrings/utf8proc/blob/93a88b43107eccf09eea399a3b7a6767092d4488/u …

Bugfix: smart-case does not work when search term contains a space

---

src/argv.c
test/regressions/github-1136-test

Our argv_format() reports success but leaves the output at null
when the input is "%(cmdlineargs)" and the corresponding option
("opt_cmdline_args") is null.
Other callers already check if the output is null, do the same.
Fixes two null dereferences in prompt.c:
:!%(cmdlineargs)
:echo %(cmdlineargs)
I don't know if there is a reproducer for the change in argv.c but
this seems better.

Fix null dereferences on unset format strings

---

src/blame.c
src/view.c

* stop clearing the history state when entering the blame view
* push a blame view history state before entering the diff view
* stop failing when trying to push an identical history state
Closes #1123

Allow :back to work across separate blame views

---

NEWS.adoc
doc/manual.adoc
doc/tigrc.5.adoc
include/tig/argv.h
include/tig/diff.h
src/diff.c
src/stage.c

This improves interaction with external tools that require file names.
Implemented by extending diff_get_pathname.
We don't handle prefixes like "diff --cc" when computing %(file_old),
because we can't tell yet if such a line is "old" or "new".
Git only uses these combined headers for binary files, and other edge
cases, see: PAGER='less +1206' git show 75ae10b:combine-diff.c
Anyway, this is not really important because %(file) already has the
correct name.
An alternative (partial) solution would be to change %(file) to the
old filename but only for deleted files. I decided against this;
while it would be convenient for some basic scenarios, it hides
information which makes scripting more difficult.
Another, more general solution for these kinds of problems would be
to allow to pipe the …

Expose %(file_old), the filename before a rename or deletion

---

src/diff.c
test/blame/initial-diff-test
test/blame/stash-test

Fixes the first issue described in https://github.com/jonas/tig/pull/1127#issuecomment-884444332

Start blame on the commit passed to a "tig show" commandline

---

src/main.c
test/main/goto-test

Hi there,
First, thank you for all the work on this awesome tool.
The one feature that I have been missing is the ability to go back to the previously selected commit after jumping to its parent.  I find that to be really useful for git repositories which are "heavily non-linear" (like the Linux kernel tree).
I see this idea has already been suggested in #628 and [also](https://github.com/jonas/tig/pull/506#issuecomment-240302791) in #506 (which implemented #388), so I took a stab at implementing it.
This PR looks almost too simple to be right, but it seems to work well for me :-)  I would be happy to work on it further if the approach I chose is not the preferred one.
Hope this helps!

Enable jumping back in main view

---

INSTALL.adoc
configure.ac
include/tig/tig.h
src/search.c

Add PCRE support

---

src/stash.c

This is a regression from #1030 due to a wrong handling of --all,
--branches, --remotes and revisions arguments in `git stash list`.
Workaround the issue by filtering them from %(revargs).
Fixes #1146

Fix stash view when using tig --all or tig revs

---

src/refdb.c
test/refs/filter-test

The environment variable TIG_LS_REMOTE can be used to select the
references that Tig will display.
When using a command like TIG_LS_REMOTE='sh -c "a | b"' tig, we pass an
argv-array with 3 elements to execvpe.  The third argument is passed
with quotes, which means that the shell tries to run a command that
is literally called 'a | b'.
Fix this by removing quotes. We already split arguments with a
shell-like syntax, so this only improves compatibility.
This makes it easier filter away unwanted refs (#1160) without creating
a script TIG_LS_REMOTE.

Remove quotes from TIG_LS_REMOTE to allow inline shell commands

---

src/argv.c
src/graph-v1.c
src/graph-v2.c
src/io.c
src/line.c
src/util.c
test/tools/test-graph.c

This pull request aims to fix null pointer dereference.
[Null pointer dereference](https://cwe.mitre.org/data/definitions/476.html)

Avoiding null pointer dereference

---

Makefile
tools/release.sh

... and replace it with new realclean rule.
Closes #1167

Update distclean rule to preserve tarball contents

---

doc/tigrc.5.adoc
include/tig/types.h
src/refdb.c
tigrc

This makes it possible to filter refs created by tools such as git-branchless
with `set reference-format = hide:other`.
Closes #1160

Add reference types stash and other

---

src/view.c

Dereference goto argument to make sure we try to reach the commit and
not the tag object for annotated tags.

Fix `:goto <tag>`

---

include/tig/view.h
src/display.c
src/view.c

The extra redrawwin() added by b445baeb8e9c67d1d3cf943e350cbd4fd0cbd174
to fix a scrolling bug in (u)xterm is causing flickering when paging
in XTerm(370).
As the original issues with xterm and gnome-terminal cannot be
reproduced anymore even on a now antique distro, revert the
associated workarounds.
Fixes #1180

Revert terminal hacks and workarounds

---

src/options.c

It seems like `git config --list` prints everything in lowercase. That results in `tig` not recognising the value of `status.showUntrackedFiles` since it's being printed as `status.showuntrackedfiles`.

Fix reading the value of `status.showUntrackedFiles`

---

src/prompt.c

Fixes https://github.com/jonas/tig/issues/1215

Avoid incorrect history path when $XDG_DATA_HOME is valid

---

src/pager.c

When working with pull requests, before merging to `master` it is nice to get the total diff of all of the commits of the PR, as in the `Files changed` tab on github. This is possible with `tig`, i.e. `git diff master | tig` or `:!git diff master`, but currently, this view does not support editing.
This PR makes editing in the pager view possible.

Can edit in Pager

---

src/tig.c

Later versions of ncurses (20111030 and up) support NCURSES_WIDECHAR even when compiling with libncurses instead of libncursesw.
Have tig correctly report whether it was linked against libncursesw or libncurses based off the same defines we set in the build script and use to determine which headers to include.
(See #1240 as an example of where `tig --version` incorrectly reports `ncursesw` instead of `ncurses`).

Correctly report which version of libncurses was linked

---

include/tig/tig.h

fixes implicit-function-declaration of strcasecmp (strings.h) and implicit define of struct timezone (bsd/gnu source)

fix some implicit declarations

---

src/stage.c

Move file_status to the function scope so it doesn't go out of scope while file_in_head is pointing to the data it contains.

Fix "dangling pointer" warning

---

include/tig/argv.h
src/argv.c

The declaration of argv_to_string() mismatched its definition. The definition had the array size, the declaration had not. Remove array sizes from all functions declared in argv.h.
Array sizes in function arguments don't ensure the code correctness but can give a wrong impression that the compiler would check the array size.

Don't use array size in function arguments

---

contrib/tig.spec.in

```
conor@dev:~$ rpmbuild -ta tig-2.5.8.tar.gz
error: bad date in %changelog: Sun 23 Feb 2014 Jonas Fonseca
```
Just needs the month and day switched around. Saw this behavior on Debian 11, SLES12, SLES15

fix date so rpmbuild completes

---

src/main.c

On musl libc `gettimeofday` (which is used by [time_now](https://github.com/jonas/tig/blob/06a1b89d98f32e9ac2d81b94515b200b0acb7dbb/src/util.c#L101)) [does not populate the timezone struct](https://git.musl-libc.org/cgit/musl/tree/src/time/gettimeofday.c?id=400c5e5c8307a2ebe44ef1f203f5a15669f20347) passed to it as [POSIX says](https://pubs.opengroup.org/onlinepubs/009604599/functions/gettimeofday.html):
> If tzp is not a null pointer, the behavior is unspecified.
[tz_minuteswest is later multiplied by 60](https://github.com/jonas/tig/blob/06a1b89d98f32e9ac2d81b94515b200b0acb7dbb/src/main.c#L136) which can overflow (if the value that happens to be in `tz_minuteswest` is large). When tig is compiled with integer overflow hardening (as is done on [Chimera Linux](https://chimera-linux.org/)) …

Initialise struct timezone in main_add_changes_commit

---

src/view.c

update_view_title can be called with a `struct view`
where `line` is NULL, and `lines` is 0.
Along this call stack:
0  update_view_title (view=0x3fdb88 <main_view>) at [...]/tig/src/view.c:690
1  0x0000000000338018 in report_clear () at [...]/tig/src/display.c:565
2  0x00000000003cfe5b in load_view (view=0x3fdb88 <main_view>, prev=0x3fdb88 <main_view>, flags=OPEN_
at [...]/tig/src/view.c:857
3  0x00000000003d0bc0 in open_view (prev=0x0, view=0x3fdb88 <main_view>, flags=OPEN_DEFAULT)
at [...]/tig/src/view.c:894
4  0x00000000003b2932 in open_main_view (prev=0x0, flags=OPEN_DEFAULT) at include/tig/main.h:57
5  0x00000000003b0cca in view_driver (view=0x0, request=REQ_VIEW_MAIN) at [...]/tig/src/tig.c:179
6  0x00000000003af96a in main (argc=1, argv=0x7fffffffddb8) at [...]/tig/src/tig.c:864 …

update_view_title: Fix NULL dereference at startup

---

src/string.c

Should cast the argument passed to is*() function in ctype.h to unsigned char.
See https://wiki.sei.cmu.edu/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char.
Should fix https://github.com/jonas/tig/issues/1294.
before:
The commit log contains Japanese characters, but they are not displayed correctly.
after:
The commit log is displayed correctly.

Fix display non-ascii character.

---

src/util.c

In addition to the fixes merged in #1299, one more fix was needed.
Before the fix, one test was failing, but after the fix, all tests passed.
```
TEST  test/tigrc/view-column-test
| Failed 1 out of 2 test(s)
| [FAIL] main-view.screen != expected/main-view.screen
| diff --git a/expected/main-view.screen b/main-view.screen
| index 53a71c6..4a307fd 100644
| --- a/expected/main-view.screen
| +++ b/main-view.screen
| @@ -1,15 +1,15 @@
|    1| 2010-04-07 MPower       Commit 10 E
|     | 2010-03-29 JTBrahe      Commit 10 D
| -  3| 2010-03-21 作者         Commit 10 C
| +  3| 2010-03-21 作           Commit 10 C
|     | 2010-03-12 RLévesque    Commit 10 B
|     | 2010-03-04 AUThor       Commit 10 A
|    6| 2010-02-23 MPower       Commit 9 E
|     | 2010-02-15 JTBrahe      Commit 9 D
| -   | 2010-02-06 …
```

One more fix display non-ascii character.

---

INSTALL.adoc
README.adoc

GitHub has dropped support for the git:// protocol:
https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/

Use HTTPS for GitHub clone URLs

---

src/blame.c
test/blame/blob-blame-test

Running
tig blame +28 tig-2.5.12 -- src/diff.c
and pressing "b" should keep the line containing "const char *diff_argv[]
= }" selected. It actually moves the selection somewhere else.
This regressed in ca0809db (Fix cursor position after "Move to parent"
in blame view, 2019-11-29).
Commit ca0809db was only about "," (":back" or ":parent").  When we press
"b" (":view-blame"), we want to use the old behavior (originally added in
ba7c7d30 (Use file and line number information when loading blame for commit,
2009-02-07)). Do that.
(Note that the behavior fixed by ca0809db regressed in 22807341 (Enable
textconv in the blame view and fix blame -L (#1190), 2022-06-03).  I have
not yet figured out what's going on, but this patch shouldn't make that worse.)
Fixes #1369

Use correct line from parent on recursive blame on blob

---

src/blame.c
test/blame/navigation-parent-test

@krobelus observed in https://github.com/jonas/tig/pull/1370 that this behavior, fixed in https://github.com/jonas/tig/commit/ca0809dbd20a31f6fa9b84c7eed5ecaa1368cd9d, regressed again in https://github.com/jonas/tig/commit/2280734104fd362a1188b0678109e01cdb9322cf.
This bug is similar to, but not identical with, https://github.com/jonas/tig/issues/1369.
The easiest way to observe the bug is to run `tig blame +28 tig-2.5.12 -- src/diff.c` and press `,` AKA `:parent`. The problem is that the view stays on line 28 instead of jumping to the corresponding line.
-----
This PR is complementary with #1370, they fix different bugs and can be merged independently. We could also decide on a different solution of changing the meaning of `blame->line`. That would also require a change to #1370.
See …

Use correct line when using `:parent` in blame view 
